### ISSUE TITLE
FPS problem

### ISSUE THREAD

**Issue by M4zz1** [GeoRCCraft/Caved-IN#13]
I dont know why but i have fps problems i have 2-3 fps all time.
Even lowered all options still have the problem.
Played modpacks like Dark Age,Industrial box,Sevtech ages and had more than 60fps always really need help with this modpack bcs it seems really really good

**Comment by GeoRCCraft** [comment]
The pack could be just a bit much for your computer. Check how much ram you have allocated (4 gigs minimum) . Reinstalling the pack could clear the problem.

**Comment by M4zz1** [comment]
nah i have 6gb rams for mincecraft to run it and 12gb in total

**Comment by GeoRCCraft** [comment]
Set the max ram to 4 gigs. Leave the minimum ram as default and try that. Don't forget to try a reinstall, that sometimes can fix issues
