### ISSUE TITLE
Server Setup

### ISSUE THREAD

**Issue by GeoRCCraft** [GeoRCCraft/Caved-IN#15]
Servers are not set up properly in the ATLauncher. Will need to properly add this for Caved IN 3

**Comment by IlikebreadYum** [comment]
What do you mean by the server not being set up properly? I made a server using ATLauncher and everything worked fine.

**Comment by GeoRCCraft** [comment]
It might be working, but I never went out of my way to set it up back end. Either way the work is currently sloppy for it and needs to be cleaned up.

**Comment by GeoRCCraft** [comment]
Cleaned up the xml for next version
